### ISSUE TITLE
cargo-deny licence advise

### ISSUE THREAD

**Issue by alekspickle** [dtolnay/unicode-ident#10]
I am really not an expert in this licence stuff, but cargo-deny advisory fails on a combination you use in this crate. :man_shrugging: 

```

 error[L001]: failed to satisfy license requirements
  ┌─ unicode-ident 1.0.2 (registry+https://github.com/rust-lang/crates.io-index):4:13
  │
4 │ license = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
  │            -^^^----^^^^^^^^^^------^^^^^^^^^^^^^^^^
  │            ││      │               │
  │            ││      │               rejected: not explicitly allowed
  │            ││      accepted: license is explicitly allowed
  │            │accepted: license is explicitly allowed
  │            license expression retrieved via Cargo.toml `license`
  │
  = unicode-ident v1.0.2

```

**Comment by dtolnay** [comment]
I believe the license is specified correctly. If somebody does not want this license in their dependencies, they should use a different crate.

**Comment by rukai** [comment]
This crate is now used by syn, so it seems that pretty much any crate that uses a proc macro must now include the unicode license.

From the readme:
> One must comply with the terms of both the Unicode License Agreement and either of the Apache license or MIT license when those generated files are involved.

I'm not quite following this, are there uses of this crate where those generated files are not involved?
